### ISSUE TITLE
please

### ISSUE THREAD

**Issue by DimonYoing** [J0k3rrWild/JailMate#1]
Make a new plugin or add it to this plugin so that the admin could put the player in jail for violating the rules , and could not break blocks there , but could walk , and when he leaves , so that the system would not block him

**Comment by J0k3rrWild** [comment]
Hello @DimonYoing 

Thank you for your suggestion, but what you wrote does not make sense, players who will be on the server will charge him, if they will not be able to do anything what are they supposed to be on the server for? Isn't that a suboptimal ban version? Why should they be on the server and charge it if it is no different from the ban command?
