### ISSUE TITLE
PlayerMoveEvent toggle

### ISSUE THREAD

**Issue by SayaAEP** [J0k3rrWild/JailMate#3]
I want this `PlayerMoveEvent` to be toggled . because I want to make a wide prison

**Comment by J0k3rrWild** [comment]
Hello!

Thank you for your suggestion.

I will add this feature for all functions when I get more time.

**Comment by sayaaep** [comment]
bruh. this was 1 year ago

**Comment by sayaaep** [comment]
this good plugin when pm3 pm4 era. i think close now
